### ISSUE TITLE
Multiline text will duplicated

### ISSUE THREAD

**Issue by rxia24** [project-yuki/YUKI#13]
As I found, the texts will emit 3 times because there a three lines, see  this "「" has repeated 3 times.

Other than tianyu's idea, I have come up with a easier one, adding a header like “!!TEXT!!” before texts emitted. So that we can track the duplicate times, then simply split the texts to get the correct texts.

I try to solve it in my machine but I can't hook the text using Hcode with node-textractor😓.

---
It support multiline game indeed, but other bug appeared.
Text will duplicate several times if there are multiline texts.
![SS](https://user-images.githubusercontent.com/22437401/60393154-4be62980-9b43-11e9-9cbe-d1243c0f2ffd.PNG)

_Originally posted by @rxia24 in https://github.com/project-yuki/YUKI/issues/11#issuecomment-507011635_

**Comment by tinyAdapter** [comment]
Do you mean that the texts are arriving in the following pattern ?

    a

    ab

    abc

    <NEXT ONE>

    d

    de

    def

    ...

If so, you can just simply remove TextMergerMiddleware because that this middleware merges several texts coming in a short period of time into one whole texts, which can be useful under the circumstance that texts are devided into parts and not come at a time, but making duplicated parts in the above condition.

**Comment by rxia24** [comment]
Exactly, if this middleware can configure, similar to TextModifierMiddleware , that will be better.
Thank you for your answer.😆
