### ISSUE TITLE
Textrator ERROR when Adding H-code

### ISSUE THREAD

**Issue by rxia24** [project-yuki/YUKI#41]
With original Textrator in /lib folder, Will pop up this error.

![image](https://user-images.githubusercontent.com/22437401/69429140-de46ce00-0d6d-11ea-8e97-c1c9ec44c661.png)

After replacing files from X86 version Textractor, problem solved.

I guess it might cause by x64 version Textractor not supporting Waffle's game.

**Comment by tinyAdapter** [comment]
I already packed x86 version of Textractor with YUKI, because most of galgames are still 32-bit.

However, Textractor packed by YUKI is a bit old (several months lacking updates), so maybe it fixed some bugs on hooking on the games you have. Still cannot verify if that is the reason, since my games here are all hooked without errors.

**Comment by rxia24** [comment]
That's wired, packedTextractor working fine with me today,

Maybe my OS has some issue, Thank you so much!
